### ISSUE TITLE
Reservation not fully completed with empty fields

### ISSUE THREAD

**Issue by minhtto** [Miguel-Graham/EECS3311_Group_Project_Workspace#63]
Configuration: Running on window 11 and java 19.0.2
Type: Bug
Can reproduce: Yes

Problem: -No error message outputted to user if we created reservation without filling in dates, even though reservation isn’t officially made
-No proper exception handling which has caused executable file to crash 

Suggested fix: Create a condition if the inputs are empty string prompt an error
Handle exception correctly

**Comment by humud99** [comment]
Hi thank you for your feedback.

We have handled this bug by adding an exception handling instead of having the program crash. Now if you decided to create the reservation without inputting dates the program will prompt the user accordingly.
