### ISSUE TITLE
Empty field on reservation number

### ISSUE THREAD

**Issue by minhtto** [Miguel-Graham/EECS3311_Group_Project_Workspace#64]
Configuration: Running on Window 11, Java Version 19.0.2
Type: Bug
Can Reproduce: Yes

Problem: If reservation number is not provided (field left empty) and search button is clicked, it will cause an exception.

Suggested fix: Need an error message instead, handle exception correctly

**Comment by humud99** [comment]
Hi thank you for your feedback.

We have handled this bug by adding an exception handling instead of having the program crash. Now if you decide to search for a reservation without inputting a reservation number the program will prompt the user accordingly.
