### ISSUE TITLE
Empty textboxes are allowed

### ISSUE THREAD

**Issue by minhtto** [Miguel-Graham/EECS3311_Group_Project_Workspace#65]
Configuration: Running on Window 11, Java Version 19.0.2
Type: Bug
Can Reproduce: Yes

Problem: Reservation is still made even though first name, last name and address is not inputted make required fields (can’t make reservation without these field)

**Comment by humud99** [comment]
Hi thank you for the feedback we have added proper error handling for such situation. now if you try making a reservation without inputting the fields required the program will display an error message.
