### ISSUE TITLE
Reservation list is not evident on usage

### ISSUE THREAD

**Issue by minhtto** [Miguel-Graham/EECS3311_Group_Project_Workspace#66]
Configuration: Running on Window 11, Java Version 19.0.2
Type: Bug
Can Reproduce: Yes

Problem: We can’t see a list of reservations anywhere so how do we use the “Find” button. It requires users to memories numbers because we don’t know a range.

Suggested fix: Create a display for the reservations, and give us an example of the input range needed to be inputted

**Comment by humud99** [comment]
Hi thank you for your feedback.

Currently we do require the front desk user of the application to memories the reservation numbers that can be obtained after successfully creating a reservation. We can create a frame to display all reservations that we have on our system, but that is a whole new user story all together in which we could implement for future iterations beyond iteration 3.
