### ISSUE TITLE
Output textbox formatting

### ISSUE THREAD

**Issue by minhtto** [Miguel-Graham/EECS3311_Group_Project_Workspace#67]
Configuration: Running on Window 11, Java Version 19.0.2
Type: Bug
Can Reproduce: Yes

Problem: 
-RoomType is not saying anything even though we made a selection
-Print output is not correct because the last name is in the same line as the header of “Customer=Profile”.
-Also services are not shown even though selected upon reservation

Suggested fix: 
-Display selection of service
-correct the print output
-make sure roomType is evident when selected

**Comment by humud99** [comment]
Hi thank you for your feedback.

We have fixed this bug by outputting the room type selected, also we have appropriately displayed the customer's first and last name, lastly the services that the client selected will be outputted in the textbox.
