### ISSUE TITLE
Phone number isn’t bounded by a certain length

### ISSUE THREAD

**Issue by minhtto** [Miguel-Graham/EECS3311_Group_Project_Workspace#68]
Configuration: Running on Window 11, Java Version 19.0.2
Type: Bug
Can Reproduce: Yes

Problem: For update reservation, the phone number has no restriction on its length unlike adding a reservation. So the same restrictions should apply for updating

Suggested fix: Bound the length of the phone number and prompt an error if less or greater than that amount

**Comment by humud99** [comment]
Hi thank you for the feedback we have added proper error handling for such situation. now if you try making a reservation without inputting the fields required the program will display an error message.

**Comment by humud99** [comment]
Hi thank you for your feedback. 

We have fixed this bug by only accepting a valid phone number, in other words bounding its length as if you were creating a new reservation, and if a user tries to input an invalid length the program will prompt the user to try again.
